### ISSUE TITLE
Move changes in SplitTransaction to secondary index code rather than the core code

### ISSUE THREAD

**Issue by ramkrish86** [Huawei-Hadoop/hindex#14]
SplitTransaction deals with ThreadLocal variables to deal with details of parent's daughter regions and the index regions's daughter regions.  
I think the CP hooks added can be contributed(may be already it is contribued) but the other changes like adding an atomic Put to the main and index region, Carrying the daughter region's info from the threadlocal has to be either moved out of the core code or we need to find a way to  make it in the core code through a CP hook.  If we go ahead with CF approach then this may not be needed.

**Comment by anoopsjohn** [comment]
The hooks around this is already conributed @chrajeshbabu , @ramkrish86 ?

**Comment by chrajeshbabu** [comment]
Not only hooks we have some changes in HRegionFileSystem#splitStoreFile to create both reference files even the split row in the hfile range...Now I have pushed the changes to hindex on top of 0.98..Hence closing

**Comment by anoopsjohn** [comment]
So no more core code changes required around the split right? We handle all coding in CP hooks correct?

**Comment by chrajeshbabu** [comment]
Yes Anoop. No more core changes around split. Remaining changes also I will bring out and push in one or two days..So that we can maintain hindex independently..
