### ISSUE TITLE
Add index related configurations to HConstants, remove year from licence in index code, make javadoc proper for {Master|Region}ObserverExt

### ISSUE THREAD

**Issue by chrajeshbabu** [Huawei-Hadoop/hindex#16]
Handle points mentioned by Ted at
https://issues.apache.org/jira/browse/HBASE-9203?focusedCommentId=13740511&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13740511 

1) add index related configurations to constants
2) remove year from licence in sec index code
3) make java doc proper for MasterObserverExt,RegionObserverExt

**Comment by anoopsjohn** [comment]
Make sure to contribute the new CP hooks to Trunk. Let us check with LarH about 94 inclusion.
We need the config  enable.secondary.index??

**Comment by chrajeshbabu** [comment]
Ok. Anoop. May be enable.secondary.index config will be better name.

**Comment by anoopsjohn** [comment]
Rajesh  I mean whether a config enable.secondary.index is really needed? Based on the CPs added the indexing solution can work?

**Comment by chrajeshbabu** [comment]
We will see, whether we can remove it fully. I will check this.

**Comment by chrajeshbabu** [comment]
Removed these kernel changes in hindex with 0.98 branch. Hence closing.
