### ISSUE TITLE
Patch file for core changes

### ISSUE THREAD

**Issue by anoopsjohn** [Huawei-Hadoop/hindex#2]
Can you create a patch for all the core changes (which are not present in 94 code base) and attach as a file in this Git?

**Comment by chrajeshbabu** [comment]
I will upload tonight.

**Comment by chrajeshbabu** [comment]
Added kernel change patch to dev-support (SecondaryIndexKernelChanges.patch)

**Comment by anoopsjohn** [comment]
Thanks Rajesh!
