### ISSUE TITLE
verify whether we can open index daughter regions before opening user regions

### ISSUE THREAD

**Issue by chrajeshbabu** [Huawei-Hadoop/hindex#20]
This helps to avoid put failures during split if user daughter regions assigned but index daughter regions assignment in progress.

**Comment by jyothi-mandava** [comment]
This will make sure that split of both index regions and user regions are complete before the Puts are accepted and thus avoid Put failures.

**Comment by chrajeshbabu** [comment]
Verified this in cluster, Its working fine. With patch no put failures and regions in transition(one odd issue with locks)
Not able to upload patch for review.
The main changes are added a hook before stepsAfterPONR
{code}
    PairOfSameType<HRegion> regions = createDaughters(server, services);
    if (this.parent.getCoprocessorHost() != null) {
      this.parent.getCoprocessorHost().preSplitAfterPONR();
    }
    stepsAfterPONR(server, services, regions);
    return regions;
{code}
Moved the code which opens index daughters and transition to znode from postSplit to new hook.

If its ok. I will commit tonight or tomorrow.

**Comment by anoopsjohn** [comment]
If things are fine, you can commit and then all will be able to see the code change from Git. Any changes can then be fixed again..

**Comment by chrajeshbabu** [comment]
ok.

**Comment by ramkrish86** [comment]
Can you just verify the history if possible, the order that is currently in the code was changed due to some bug.  I don't remember it correctly.  If the issue fixes the problem then no issues.  Just check to verify incase any other issues hidden.  Thanks for the fix

**Comment by chrajeshbabu** [comment]
Ram, checked the issues related to split, we didn't try this order(index regions assignments first). Any way testing all scenarios like puts,scans during split and restart cases as well. All are fine till now.

**Comment by chrajeshbabu** [comment]
committed the changes. closing this issue.
