### ISSUE TITLE
Have separate split policy for index regions. 

### ISSUE THREAD

**Issue by chrajeshbabu** [Huawei-Hadoop/hindex#25]
Presently while doing split from external client or after compaction, we are having a check for index table region, which is kernel change. Instead we can define a split policy which will return false on explicit split.

**Comment by anoopsjohn** [comment]
+1.

**Comment by ramkrish86** [comment]
+1

**Comment by chrajeshbabu** [comment]
It's added in hindex with 0.98 branch.
https://github.com/Huawei-Hadoop/hindex/tree/hbase-0.98
