### ISSUE TITLE
postStartRegionOperation in batchMutate should call in try block.

### ISSUE THREAD

**Issue by chrajeshbabu** [Huawei-Hadoop/hindex#26]
presently we are calling postStartRegionOperation as after startRegionOperation.
{code}
      startRegionOperation();

```
  if (coprocessorHost != null) {
    coprocessorHost.postStartRegionOperation();
  }
```

{code}

In startRegionOperation we are aquiring read lock. If any exceptions in postStartRegionOperation we will throw out the exception and the lock wont be released. This will cause block region closing or other operations which needs write lock.

If we call this in try block then we can release the lock in closeRegionOperation.

Some test cases are hanging while closing all regions in shutdown because of this issue.

**Comment by anoopsjohn** [comment]
Need to fix this in the HBase jira patch?

**Comment by chrajeshbabu** [comment]
Yes Anoop, patch also need to be updated.

**Comment by hy2014** [comment]
hi, 
how to fix the issue? i get the problem when do put operation.

**Comment by chrajeshbabu** [comment]
We have fix for this..missed to commit here. We will commit today..

**Comment by chrajeshbabu** [comment]
@hy2014 
We have fixed now. Can you try now with latest build. Thanks

**Comment by hy2014** [comment]
yes, i have try it, it is ok.
