### ISSUE TITLE
I hadn't found the api of "admin.createTable(desc, startKey, endKey, numRegions)"

### ISSUE THREAD

**Issue by edmund2004** [Huawei-Hadoop/hindex#31]
I think the api is so import to begioning .And another question is What time the second
can support Hadoop 2.X.
Thank you

**Comment by chrajeshbabu** [comment]
The createTable API you are telling is available in HBaseAdmin. If you want to create table with index , create IndexedHTableDescriptor.

  public void createTable(HTableDescriptor desc, byte [] startKey,
      byte [] endKey, int numRegions)

If your hadoop cluster is Hadoop 2.x then you can build by specifying hadoop profile 2.0
Ex; mvn clean package -DskipTests -Dhadoop.profile=2.0
