### ISSUE TITLE
hindex compare to phoenix secondary index

### ISSUE THREAD

**Issue by hnucsbjd** [Huawei-Hadoop/hindex#32]
hindex compare to  phoenix secondary index(https://github.com/forcedotcom/phoenix
),there are some advantages and defects? combine phoenix's sql  and hindex's secondary index is a good scheme?

**Comment by anoopsjohn** [comment]
Latest release of Phoenix comes with secondary index feature in it.

<i>combine phoenix's sql and hindex's secondary index is a good scheme?</i>
+1

**Comment by hnucsbjd** [comment]
Phoenix indexes are global indexes, while Huawei indexes are local. Both are good in different use cases.

**Comment by anoopsjohn** [comment]
Yes Phoenix having global indexes only as of now. It will be good to add local indexing facility also into Phoenix so that as per use case one can select either of these.    Integration of HIndex with Phoenix will be a good choice. Any help in this regard is most welcome. :)

**Comment by anoopsjohn** [comment]
Rajesh is doing the integration of HIndex into Phoenix.  Closing this issue.
