### ISSUE TITLE
auto index the table after modify the table

### ISSUE THREAD

**Issue by hy2014** [Huawei-Hadoop/hindex#33]
If we create table first and there are some data in the table,  now we want to use hindex, I use HtableAdmin.modifyAdmin method, it can create the index table, but it cannot index the data already exist in the table, is there some method to resolve this issues.?

**Comment by chrajeshbabu** [comment]
You can use org.apache.hadoop.hbase.index.mapreduce.TableIndexer
mapreduce job to create index table and index the data already exists. You can see the usage of it for more detail. Thanks.
