### ISSUE TITLE
TableIndexer cannot index data

### ISSUE THREAD

**Issue by hy2014** [Huawei-Hadoop/hindex#34]
when I run this mapreduce job, I found it can read from hbase table, but the map output is 0. 
I found it always return null when execute IndexUtils.getIndexedHTableDescriptor(tablename, conf) method. So mapper cannot output any records to reducer.

**Comment by chrajeshbabu** [comment]
Let us check and fix it quickly. Thanks for reporting.

**Comment by anoopsjohn** [comment]
Is this table IndexedHTableDesc now?   Can u try alter the table with IndexedHTableDesc once and then do the run of the MR?

**Comment by hy2014** [comment]
Yes, after run the map/reduce job, it can create a index table. But when run the map/reduce job, it try to find the IndexHtableDesc from /tmp/hbase-${user}/${table-name}/.tableinfo path, but I cannot find it from the local machine. So it always return null.

**Comment by chrajeshbabu** [comment]
From TableIndexer before running mapreduce job, we are creating index table
    String tableNameToIndex = tableName[0];
    IndexUtils.createIndexTable(tableNameToIndex, conf, cfs);
    createMapReduceJob(tableNameToIndex, conf, caching, versions);

So there should be index table present always.
One more thing is you are using standalone hbase cluster?
This means your mapreduce job will run in local mode right?

**Comment by hy2014** [comment]
1. yes, though no data been put into hbase, but the index table can be create in the hbase.

2.I do not use standlone hbase cluster, I have one master and three region server, and the hadoop is also cluster mode, there are three datanode.

**Comment by chrajeshbabu** [comment]
I see.
I thought its standalone mode by seeing this path /tmp/hbase-${user}/${table-name}/.tableinfo
Any way we have just now also tested. Its working fine in our case. Can you tell your configurations?

**Comment by hy2014** [comment]
It return null at execute IndexUtils.getTableInfoFilePat(),  
when execute 
Path path = FSUtils.getTablePath(FSUtils.getRootDir(conf), tableName); 
So i print the path, it output: /tmp/hbase-${user}/..../.tableinfo.
I donot know this path is hdfs or local path. 
Ask a question, you will save index table desc in some tmp path？But i cannot find them both in hdfs and local machine file system.

**Comment by hy2014** [comment]
which configuration do you mean? hbase cluster or map/reduce?
hbase cluster configuration just as normal.
map/reduce I extractor com.apache.hadoop.hbase.filter and com.apache.hadoop.hbase.index these two package and  build the jar with 
<configuration>
  <property>
    <name>hbase.zookeeper.quorum</name>
    <value>ubuntu-zk1</value>
  </property>
  <property>
    <name>tablename.to.index</name>
    <value>....</value>
  </property>

```
<property>
<name>table.columns.index</name>
<value>....</value>
```

  </property>

```
<property>
   <name>hbase.defaults.for.version.skip</name>
   <value>true</value>
</property>
```

</configuration>
and run the map/reduce job.

**Comment by chrajeshbabu** [comment]
We are storing any thing tmp directory. Index table will be created as normal table by master.
The path is default path from hbase-default.xml
  <property>
    <name>hbase.rootdir</name>
    <value>file:///tmp/hbase-${user.name}/hbase</value>
  </property>
It should be configured in hbase-site.xml with hbase root directory in hdfs(Ex: hdfs://ip:port/hbase)
Can you check hbase-site.xml configurations are loaded properly while initializing job?

**Comment by hy2014** [comment]
OK, i get the reason. I think the hbase.rootdir should be the cluster configuration, so i do not configure it in the map/reduce job. After configure it correctly, it can index the data. Sorry for that.

**Comment by hy2014** [comment]
thank you very much!

**Comment by chrajeshbabu** [comment]
No problem. Thanks
