### ISSUE TITLE
hindex supports CDH4 hbase  ？

### ISSUE THREAD

**Issue by arronli** [Huawei-Hadoop/hindex#36]
i found some interfaces not implemented when compiled with eclipse using cdh4.3.0 hbase jars ，
does hindex  take supportting CDH4 hbase into consideration ？

**Comment by hnucsbjd** [comment]
can you list the not implemented interfaces?

**Comment by anoopsjohn** [comment]
There is an impl for HIndex based on 0.98 HBase. @chrajeshbabu  can u paste the url?  
CDH 5.x is based on 0.98  can you check and try using it?
HBase 0.96 is already EOL.

**Comment by xuxc** [comment]
https://github.com/Huawei-Hadoop/hindex/tree/hbase-0.98‍

------------------ 原始邮件 ------------------
发件人: "Anoop Sam John";notifications@github.com;
发送时间: 2014年11月5日(星期三) 下午4:16
收件人: "Huawei-Hadoop/hindex"hindex@noreply.github.com; 
抄送: "xuxc"xuxc1120@hotmail.com; 
主题: Re: [hindex] hindex supports CDH4 hbase ？ (#36)

There is an impl for HIndex based on 0.98 HBase. @chrajeshbabu  can u paste the url?

 CDH 5.x is based on 0.98  can you check and try using it?
 HBase 0.96 is already EOL.

**Comment by anoopsjohn** [comment]
Pls try using this. I dont think we can give HIndex based on 0.96 as it is already EOL
