### ISSUE TITLE
migrate hindex to hbase 0.96 or higher

### ISSUE THREAD

**Issue by tenggyut** [Huawei-Hadoop/hindex#44]
is it possible to migrate hindex to a higher version of hbase,like 0.96?

based on my understanding, there is a huge difference between 0.96 and 0.94.8, like project structure's changing, some core api's changing etc..

how can i merge the hindex's code into hbase 0.96?

Thank you

**Comment by chrajeshbabu** [comment]
Hi tenggyut,
The work is in progress for HBase latest code.
The patch working with latest code is available at this location https://issues.apache.org/jira/browse/HBASE-10222

It might be better to create separate branches here for versions like 0.96 and above. I will try to make them soon. 

Thanks for your interest.

**Comment by tenggyut** [comment]
hi,

Thank you for such a quick response!

after your comment, i took some time and finally managed to merge hindex's code into hbase 0.98.1(release version). All of the test cases are passed during the building process, so exciting by the way...

So is this safe to say the patching work is done and this hbase build is kind of stable?

**Comment by chrajeshbabu** [comment]
bq. So is this safe to say the patching work is done and this hbase build is kind of stable?
Everything should work fine. Thanks for using it.

**Comment by anoopsjohn** [comment]
Do we have a branch based on HBase 0.98 here in Git @chrajeshbabu ?
Pls publish the url so that we can close this issue.

**Comment by chrajeshbabu** [comment]
Here is the hindex with 0.98 branch.
https://github.com/Huawei-Hadoop/hindex/tree/hbase-0.98
