### ISSUE TITLE
how to use the index?

### ISSUE THREAD

**Issue by xuxc** [Huawei-Hadoop/hindex#47]
and how to deploy the hindex into cluster，or just like hbase 0.90.4? and how to bulid the project?..
and can it works with hadoop 1.X?

**Comment by chrajeshbabu** [comment]
Yes you start deploy cluster like 0.90.4.
Currently it's supported on top of HBase 0.94.8.
To build hindex, you can run "mvn clean package -DskipTests" as how we build hbase. By default it works with hadoop 1.x.

**Comment by xuxc** [comment]
thx for u answer,
that's to say: i need to build hbase0.94.8 firstly,and then build hindex? or just build hindex and deploy it?

**Comment by chrajeshbabu** [comment]
just build hindex and deploy it. Thanks

**Comment by xuxc** [comment]
hi,
i'd like to know how index region's rowkey change when user region split,
i found the pic in pdf namely SecondaryIndex Design.pdf:
Note that index table's rowkeys are start with "001",but such region after split is start with "005",
is something wrong in that PDF?
if so, how to change index region's rowkey like "001_idxname_value_key" to "005_idxname_value_key"?  ("005" means the index region's start key)

thank you!

**Comment by anoopsjohn** [comment]
After split HBase will kick start a compaction. As u know the split will create ref files and reading from those files use HalfStoreFileReader.    The compaction will use these readers and do actual split of the file into 2.
In case of index region split we will use Special halfStoreFileReader. This reader when output the Cells during compaction will do this rewrite of 001->005

**Comment by xuxc** [comment]
that's to say,when compacting Cells ,Special halfStoreFileReader will put a new rowkey ("005_idxname_value_key" ) instead of old one for a particular row?

**Comment by anoopsjohn** [comment]
Yes. The special reader will output cell with replaced rk.  001 part will be replaced to 005 (as that is the start key now)

**Comment by xuxc** [comment]
Hi ,
i'd like to know is it possible to change HRegion's split threshold dynamically？
i.e I use some algorithm like genetic algorithm to modify split threshold without manual intervention，
if so, what should I focus on？
thanks ,
xuxc
12.16
