### ISSUE TITLE
is there any new release based on hbase0.98.1+?

### ISSUE THREAD

**Issue by xuxc** [Huawei-Hadoop/hindex#51]
is there any new release based on hbase0.98.1+,and any new hindex release for phoenix?

**Comment by anoopsjohn** [comment]
New Phoenix 4.x versions include HIndex integration. 4.2 Phoenix release will be coming in a week time.
There is no release of HIndex as such based on 0.98.   Can we think for it @chrajeshbabu @ramkrish86 ?

**Comment by chrajeshbabu** [comment]
Here is hindex on top of 0.98.3
https://github.com/Huawei-Hadoop/hindex/tree/hbase-0.98

**Comment by xuxc** [comment]
thank you for kindness.
