### ISSUE TITLE
ERRORs in building with CDH5.1

### ISSUE THREAD

**Issue by xuxc** [Huawei-Hadoop/hindex#52]
i Download the hindex-hbase-0.98 and used maven to build it:  
    mvn clean package -DskipTests -Dhadoop.profile=2.0
But errors here:
[ERROR]   The project org.apache.hbase:hbase:0.98.3 (D:\hindex-hbase-0.98\pom.xm
l) has 2 errors
[ERROR]     'dependencyManagement.dependencies.dependency.artifactId' for org.ap
ache.hbase:${compat.module}:jar with value '${compat.module}' does not match a v
alid id pattern. @ line 998, column 21
[ERROR]     'dependencyManagement.dependencies.dependency.artifactId' for org.ap
ache.hbase:${compat.module}:test-jar with value '${compat.module}' does not matc
h a valid id pattern. @ line 1003, column 21

is something incorrect ?

**Comment by xuxc** [comment]
@chrajeshbabu @jyothi-mandava 

thanks.

**Comment by chrajeshbabu** [comment]
By default it it will build with hadoop 2. So need not mention hadoop.profile=2.0 which is not there
Just try mvn clean install -DskipTests -Passembly:single to get tar.gz

If it works for you just close it.
Thanks.

**Comment by xuxc** [comment]
main:
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] HBase .............................................. SUCCESS [  2.418 s]
[INFO] HBase - Common ..................................... FAILURE [  0.683 s]
[INFO] HBase - Protocol ................................... SKIPPED
[INFO] HBase - Client ..................................... SKIPPED
[INFO] HBase - Hadoop Compatibility ....................... SKIPPED
[INFO] HBase - Hadoop Two Compatibility ................... SKIPPED
[INFO] HBase - Prefix Tree ................................ SKIPPED
[INFO] HBase - Server ..................................... SKIPPED
[INFO] HBase - Testing Util ............................... SKIPPED
[INFO] HBase - Thrift ..................................... SKIPPED
[INFO] HBase - Shell ...................................... SKIPPED
[INFO] HBase - Integration Tests .......................... SKIPPED
[INFO] HBase - Examples ................................... SKIPPED
[INFO] HBase - Secondary Index ............................ SKIPPED
[INFO] HBase - Assembly ................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.622 s
[INFO] Finished at: 2014-10-29T20:23:12+08:00
[INFO] Final Memory: 25M/59M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.6:
run (generate) on project hbase-common: An Ant BuildException has occured: Execu
te failed: java.io.IOException: Cannot run program "bash" (in directory "D:\hind
ex-hbase-0.98\hbase-common"): CreateProcess error=2, ????????? -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionE
xception
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command

[ERROR]   mvn <goals> -rf :hbase-common

does it failed because of JDK1.7?

**Comment by chrajeshbabu** [comment]
no. Are you trying to build in windows or linux?

**Comment by xuxc** [comment]
oh~~The bad network caused it! 
Now i have built success,and each subproject has a "target",and there is no "lib" under project root folder,
do i need copy *.jar to lib ,or just deploy it when i build success?

**Comment by xuxc** [comment]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] HBase .............................................. SUCCESS [  3.817 s]
[INFO] HBase - Common ..................................... SUCCESS [04:51 min]
[INFO] HBase - Protocol ................................... SUCCESS [ 11.046 s]
[INFO] HBase - Client ..................................... SUCCESS [ 28.157 s]
[INFO] HBase - Hadoop Compatibility ....................... SUCCESS [  0.333 s]
[INFO] HBase - Hadoop Two Compatibility ................... SUCCESS [ 26.262 s]
[INFO] HBase - Prefix Tree ................................ SUCCESS [  2.326 s]
[INFO] HBase - Server ..................................... SUCCESS [03:39 min]
[INFO] HBase - Testing Util ............................... SUCCESS [ 13.042 s]
[INFO] HBase - Thrift ..................................... SUCCESS [ 57.344 s]
[INFO] HBase - Shell ...................................... SUCCESS [07:08 min]
[INFO] HBase - Integration Tests .......................... SUCCESS [  1.806 s]
[INFO] HBase - Examples ................................... SUCCESS [  1.913 s]
[INFO] HBase - Secondary Index ............................ SUCCESS [ 14.094 s]
[INFO] HBase - Assembly ................................... SUCCESS [  2.774 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 18:24 min
[INFO] Finished at: 2014-10-30T11:26:09+08:00
[INFO] Final Memory: 59M/305M
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[WARNING] The requested profile "assembly:single" could not be activated because it does not exist.

hadoop@namenode:~/hindex-hbase-0.98$ ll
总用量 336
drwxr-xr-x 22 hadoop hadoop   4096 10月 30 11:07 ./
drwxr-xr-x 37 hadoop hadoop   4096 10月 30 10:37 ../
-rwxr-xr-x  1 hadoop hadoop    395 10月 29 14:11 .arcconfig*
drwxr-xr-x  4 hadoop hadoop   4096 10月 29 14:11 bin/
-rwxr-xr-x  1 hadoop hadoop 127483 10月 29 14:11 CHANGES.txt*
drwxr-xr-x  2 hadoop hadoop   4096 10月 29 14:11 conf/
drwxr-xr-x  3 hadoop hadoop   4096 10月 29 14:11 dev-support/
-rwxr-xr-x  1 hadoop hadoop   1015 10月 29 14:11 .gitattributes*
-rwxr-xr-x  1 hadoop hadoop    147 10月 29 14:11 .gitignore*
drwxr-xr-x  4 hadoop hadoop   4096 10月 30 11:26 hbase-assembly/
drwxr-xr-x  4 hadoop hadoop   4096 10月 30 11:13 hbase-client/
drwxr-xr-x  4 hadoop hadoop   4096 10月 30 11:09 hbase-common/
drwxr-xr-x  4 hadoop hadoop   4096 10月 30 11:25 hbase-examples/
drwxr-xr-x  3 hadoop hadoop   4096 10月 29 14:11 hbase-hadoop1-compat/
drwxr-xr-x  4 hadoop hadoop   4096 10月 30 11:13 hbase-hadoop2-compat/
drwxr-xr-x  4 hadoop hadoop   4096 10月 30 11:13 hbase-hadoop-compat/
drwxr-xr-x  4 hadoop hadoop   4096 10月 30 11:25 hbase-it/
drwxr-xr-x  4 hadoop hadoop   4096 10月 30 11:13 hbase-prefix-tree/
drwxr-xr-x  4 hadoop hadoop   4096 10月 30 11:12 hbase-protocol/
drwxr-xr-x  4 hadoop hadoop   4096 10月 30 11:26 hbase-secondaryindex/
drwxr-xr-x  4 hadoop hadoop   4096 10月 30 11:16 hbase-server/
drwxr-xr-x  4 hadoop hadoop   4096 10月 30 11:25 hbase-shell/
drwxr-xr-x  3 hadoop hadoop   4096 10月 30 11:17 hbase-testing-util/
drwxr-xr-x  4 hadoop hadoop   4096 10月 30 11:18 hbase-thrift/
-rwxr-xr-x  1 hadoop hadoop  11358 10月 29 14:11 LICENSE.txt*
-rwxr-xr-x  1 hadoop hadoop    897 10月 29 14:11 NOTICE.txt*
-rwxr-xr-x  1 hadoop hadoop  78678 10月 29 14:11 pom.xml*
-rwxr-xr-x  1 hadoop hadoop   5466 10月 29 14:11 README.md*
-rwxr-xr-x  1 hadoop hadoop   1377 10月 29 14:11 README.txt*
drwxr-xr-x  3 hadoop hadoop   4096 10月 29 14:11 src/
drwxrwxr-x  3 hadoop hadoop   4096 10月 30 11:26 target/

hadoop@namenode:~/hindex-hbase-0.98$ cd target/
hadoop@namenode:~/hindex-hbase-0.98/target$ ll
总用量 32
drwxrwxr-x  3 hadoop hadoop  4096 10月 30 11:26 ./
drwxr-xr-x 22 hadoop hadoop  4096 10月 30 11:07 ../
-rw-rw-r--  1 hadoop hadoop 10499 10月 30 11:26 cached_classpath.txt
-rw-rw-r--  1 hadoop hadoop  4003 10月 30 11:07 hbase-0.98.3-site.xml
drwxrwxr-x  3 hadoop hadoop  4096 10月 30 11:07 maven-shared-archive-resources/
-rw-rw-r--  1 hadoop hadoop    30 10月 30 11:07 .plxarc

there is no "lib" in the folder.and how to deploy hindex-0.98?
thank you , @chrajeshbabu @jyothi-mandava

**Comment by chrajeshbabu** [comment]
In hbase-aseembly/target you should get tar.gz

**Comment by xuxc** [comment]
yeah, after decompress the tar.gz, the folder total 70.3 MB,and files as follows:
hadoop@namenode:~/hindex-hbase-0.98/hbase-assembly/target/hbase-0.98.3$ ll
总用量 172
drwxrwxr-x 6 hadoop hadoop   4096 10月 30 12:27 ./
drwxrwxr-x 5 hadoop hadoop   4096 10月 30 12:27 ../
drwxr-xr-x 4 hadoop hadoop   4096 10月 29 14:11 bin/
-rw-r--r-- 1 hadoop hadoop 127483 10月 29 14:11 CHANGES.txt
drwxr-xr-x 2 hadoop hadoop   4096 10月 29 14:11 conf/
drwxr-xr-x 7 hadoop hadoop   4096 10月 30 12:25 hbase-webapps/
drwxrwxr-x 3 hadoop hadoop   4096 10月 30 12:27 lib/
-rw-r--r-- 1 hadoop hadoop  11358 10月 29 14:11 LICENSE.txt
-rw-r--r-- 1 hadoop hadoop    897 10月 29 14:11 NOTICE.txt
-rw-r--r-- 1 hadoop hadoop   1377 10月 29 14:11 README.txt

there is no "secondaryindex" and "docs" folder such as hindex-0.94,is this correct?

**Comment by chrajeshbabu** [comment]
Now secondary index is submodule in the proble so you can find hbase-secondaryindex-0.98.3 in lib folder.
Just FYI, there are some configuration changes and client side changes required for 0.98 which are not changed in the document.

See TestIndexRegionObserver#testMultipleIndicesOnUniqueColumns to check how to create indexes from client.

and here are the server side configurations

```
    <property>
            <name>hbase.coprocessor.master.classes</name>
            <value>org.apache.hadoop.hbase.index.coprocessor.master.IndexMasterObserver</value>
    </property>

    <property>
            <name>hbase.coprocessor.region.classes</name>
            <value>org.apache.hadoop.hbase.index.coprocessor.regionserver.IndexRegionObserver</value>
    </property>
    <property>
            <name>hbase.coprocessor.wal.classes</name>
            <value>org.apache.hadoop.hbase.index.coprocessor.wal.IndexWALObserver</value>
    </property>

    <property>
            <name>hbase.use.secondary.index</name>
            <value>true</value>
    </property>
    <property>
            <name>hbase.master.loadbalancer.class</name>
            <value>org.apache.hadoop.hbase.index.SecIndexLoadBalancer</value>
    </property>
```

Thanks.

**Comment by xuxc** [comment]
got it,

thank you very much.
