### ISSUE TITLE
CP hook for IndexHalfStoreFileReader

### ISSUE THREAD

**Issue by anoopsjohn** [Huawei-Hadoop/hindex#8]
Now the creation of this new class/ HalfStoreFileReader is happening (to read half files) based on checks on table name in core code.  Can check adding a CP hook in core code and implementing this using the new CP hook.

**Comment by chrajeshbabu** [comment]
+1

**Comment by anoopsjohn** [comment]
HBASE-9244 will provide the new hook. Once that is in place we can change the impl by using the hook

**Comment by anoopsjohn** [comment]
This new hook is already available in 98 versions of HBase. Have we changed HIndex code to make use of the CP hook and avoid the core code change?  @chrajeshbabu ?

**Comment by chrajeshbabu** [comment]
Yes @anoopsjohn, Making use of it in 0.98 branch.
